---
title: "Examen_Estadística_Computacional"
author: "Miguel Ángel Ávila del Bosque Mario Alberto Cruz García Javier Valencia Goujón"
date: "11/10/2019"
output: html_document
---
## Examen Parcial de Estadística Computacional
## Profesor: Dr. León Berdichevsky Acosta

```{r warning=FALSE}
library(tidyverse)
library(ggplot2)
library(datasets)
```

### Pregunta 1
```{r warning=FALSE}
data(iris)
glimpse(iris)
head(iris)

# a). Al parecer cuple con los principios de datos limpios. 
# Los datos se encuentran ordenados por columnas y no hay más de una variable en una columna.
# Cada observacón forma un renglón.
# Cada tipo de unidad observacional forma una tabla.

# b). No estoy seguro si no cumple los principios por esta pregunta.
head(iris, n = 6)

# c).
glimpse(iris)
# 5 variables con 150 observaciones.

class(iris)

# length, width, petal.lenght, petal.length double y species <ftc> similar a 
# cadena de caracteres.

setosa <- filter(iris, Species == "setosa")
head(setosa, n = 6)

setosa_desc <- arrange(setosa, desc(Petal.Length))
head(setosa_desc, n = 6)

setosa_mm <- mutate(setosa_desc, Petal.Length_mm = Petal.Length * 10)
head(setosa_mm)

setosa_NAs <- gather(setosa_mm, Petal.Length, na.rm = TRUE)
head(setosa_NAs)

ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color = Species)) +
  geom_point()

ggplot(iris, aes(x = Petal.Length, y = Petal.Length, color = Species)) +
  geom_boxplot()

rpoisI <- function(lambda = 1){
  U <- runif(1)
  i <- 0
  p <- exp(-lambda)
  P <- p
  while(U >= P){
    p <- lambda * p / (i + 1)
    P <- P + p
    i <- i + 1
  }
  i
}
sims_pois <- rerun(1000, rpoisI()) %>% flatten_dbl()
qplot(sims_pois, binwidth = 1)

plot(sims_pois, 1:1000)
```

### Pregunta 2
```{r warning=FALSE}

```

### Pregunta 3
```{r warning=FALSE}

```

### Pregunta 4
```{r warning=FALSE}
lambda <- 2.5
calcula_intervalos <- function(n = 60, B = 10000) {
  x <- rpois(n, lambda)
  theta <- exp(-2 * mean(x))
  theta_b <- rerun(B, sample(x, size = n, replace = TRUE)) %>% 
    map_dbl(~exp(-2 * mean(.)))
  bca <- bootstrap::bcanon(x, nboot = B, theta = function(y) exp(-2 * mean(y)), 
                           alpha = c(0.025, 0.975))$confpoints[, 2]
  intervalos <- data_frame(metodo = c("normal", "percent", "BC_a"), 
                           izq = c(theta - 1.96 * sd(theta_b), quantile(theta_b, probs = 0.025), 
                                   bca[1]),
                           der = c(theta + 1.96 * sd(theta_b), quantile(theta_b, probs = 0.975), 
                                   bca[2])
  )
  list(theta = theta, intervalos = intervalos)
}

set.seed(83789173)
n_sims <- 500
sims_intervalos_60 <- rerun(n_sims, calcula_intervalos()) 
#write_rds(sims_intervalos_60, path = "sims_intervalos_60.rds") 
#sims_intervalos_60 <- read_rds("data/sims_intervalos_60.rds")
sims_intervalos_60 %>% 
  map_df(~.$intervalos) %>% 
  group_by(metodo) %>%
  summarise(
    falla_izq = 100 * sum(izq > exp(-2 * lambda)) / n_sims, 
    falla_der = 100 * sum(der < exp(-2 * lambda)) / n_sims, 
    cobertura = 100 - falla_izq - falla_der, 
    long_media = mean(der - izq),
    long_min = min(der - izq),
    long_max = max(der - izq)
  )

intervalos_muestra <- sims_intervalos_60 %>% 
  map_df(~.$intervalos) %>% 
  mutate(sim = rep(1:n_sims, each = 3)) %>% 
  filter(sim <= 500) %>% 
  mutate(
    sim_factor = reorder(sim, der - izq), 
    sim = as.numeric(sim_factor)
  )
thetas <- sims_intervalos_60 %>% 
  map_dbl(~.$theta) 

thetas_df <- data_frame(thetas = thetas, sim = 1:n_sims) %>% 
  mutate(
    sim_factor = factor(sim, 
                        levels = levels(intervalos_muestra$sim_factor)), 
    sim = as.numeric(sim_factor)
  ) %>% 
  dplyr::filter(sim <= 500) 

ggplot(intervalos_muestra) +
  geom_hline(yintercept = exp(-2 * 2.5), alpha = 0.6) +
  geom_line(aes(x = sim, y = izq), color = "red", alpha = 0.5) +
  geom_line(aes(x = sim, y = der), color = "red", alpha = 0.5) +
  geom_line(data = thetas_df, aes(x = sim, y = thetas), color = "blue", 
            alpha = 0.5) +
  facet_wrap(~ metodo, ncol = 1)
```

### Pregunta 5
```{r warning=FALSE}
set.seed(6221285)

# Prueba con P_i y i = 1,2,3,...
# Son los resultados más consistentes pero no sé si esté bien
rBinNegII <- function(n = 10, pe = 0.3){
  U <- runif(1)
  i <- 1
  p <- pe^n
  P <- p
  while (U >= P) {
    p <- p * (1 - pe) * ((i + n - 1) / (i))
    P <- P + p
    i <- i + 1
  }
  i
}
sims_binNeg_II <- rerun(10000, rBinNegII()) %>% flatten_dbl()
head(sims_binNeg_II, n = 5)

qplot(sims_binNeg_II, binwidth = 1)
```

